const IMAGES = {
  cashiering_billing: require("./cashiering_billing.png"),
  cashiering_cashier_functions: require("./cashiering_cashier_functions.png"),
  cashiering_cashier_shift_functions: require("./cashiering_cashier_shift_functions.png"),
  cashiering_fast_posting: require("./cashiering_fast_posting.png"),
  cashiering_passer_by: require("./cashiering_passer_by.png"),
  cashiering_post_it: require("./cashiering_post_it.png"),
  cashiering_quick_checkout: require("./cashiering_quick_checkout.png"),
  front_desk_accounts: require("./front_desk_accounts.png"),
  front_desk_arrivals: require("./front_desk_arrivals.png"),
  front_desk_inhouse_guests: require("./front_desk_inhouse_guests.png"),
  front_desk_messages: require("./front_desk_messages.png"),
  front_desk_queue_reservations: require("./front_desk_queue_reservations.png"),
  front_desk_room_assignment: require("./front_desk_room_assignment.png"),
  front_desk_traces: require("./front_desk_traces.png"),
  front_desk_wakeup_calls: require("./front_desk_wakeup_calls.png"),
  nav_ar: require("./nav_ar.png"),
  nav_cashiering: require("./nav_cashiering.png"),
  nav_end_of_day: require("./nav_end_of_day.png"),
  nav_exit: require("./nav_exit.png"),
  nav_front_desk: require("./nav_front_desk.png"),
  nav_miscellaneous: require("./nav_miscellaneous.png"),
  nav_reservations: require("./nav_reservations.png"),
  nav_rooms_management: require("./nav_rooms_management.png"),
  reservations_blocks: require("./reservations_blocks.png"),
  reservations_calendar: require("./reservations_calendar.png"),
  reservations_confirmation: require("./reservations_confirmation.png"),
  reservations_floor_plan: require("./reservations_floor_plan.png"),
  reservations_new_reservation: require("./reservations_new_reservation.png"),
  reservations_profiles: require("./reservations_profiles.png"),
  reservations_registration_cards: require("./reservations_registration_cards.png"),
  reservations_room_plan: require("./reservations_room_plan.png"),
  reservations_update_reservation: require("./reservations_update_reservation.png"),
};
export default IMAGES;
